name: music_player

description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  marquee: ^2.2.3
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  permission_handler: ^10.2.0
  lecle_yoyo_player: ^0.0.5+2
  http: ^0.13.6
  html: ^0.15.2
  # audioplayers: ^4.0.1  
  just_audio: ^0.9.28
  on_audio_query: ^2.6.1
  audio_service: ^0.18.9

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/   


  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 600 
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500 